export const host = "http://localhost:8080";
export const loginRoute = `${host}/api/auth/login`;
export const registerRoute = `${host}/api/auth/register`;
//export const host = "http://localhost:3000";
export const productroute=`${host}/product`;
export const updateroute=`${host}/product/update/`;
export const viewroute=`${host}/product/view/`;
export const reviewroute=`${host}/product/review/`;
export const cartroute=`${host}/user/add/`
export const getcartitem=`${host}/user/cart`;
export const addproduct=`${host}/products/new`;
export const userroute=`${host}/user/info/`;
export const deleteCartItemRoute=`${host}/user/cart/dele`;
export const deleteproduct=`${host}/product/delete`